apiVersion: v2
appVersion: "1.0"
description: A wrapper chart for eric-enm-ingress-controller-nx
name: eric-enm-int-ingress-controller-nx
version: 1.0.0
dependencies:
- condition: eric-enm-common-helmchart-library.enabled
  name: eric-enm-common-helmchart-library
  repository: https://arm.epk.ericsson.se/artifactory/proj-enm-helm/
  version: 1.55.0-5